# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d715a5b027fa7b36dccab39036cda7320ac932e249a5ffada8e36da9cf0a88ddf8da5413db677da12251c1654b43f868a06715fe38383c4529eb2c48318ad6

test:
  secret_key_base: e075a260c3e6533958d9d81e5de2a7c196325ce6cb0c5afc73f85f7f7719fd2fba99d0445f2dced915d7e3b7a703347d4552dbddbfa4f34c33d2bca2213844a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
